# .github/workflows/docker-image.yml
name: Docker Image CI
on:
  push: #any push to the main branch will trigger this workflow
    branches:
      - main
  pull_request: #any pull request to the main branch will trigger this workflow
    branches:
      - main

permissions: 
  contents: read
  packages: write

jobs:
  build: #job name
    runs-on: ubuntu-latest  #the job will run on the latest version of Ubuntu
    #   the steps to be executed in the job
    steps:
    - name: Checkout code  #this step checks out the code from the repository so that it can be used in the subsequent steps
      uses: actions/checkout@v3

    - name: Set up Docker Buildx  #this step sets up Docker Buildx, which is a tool that allows you to build and push multi-platform Docker images
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry #this step logs in to the GitHub Container Registry using the provided credentials, allowing the workflow to push Docker images to the registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }} #the username is set to the repository owner, which is the GitHub account that owns the repository
        password: ${{ secrets.GITHUB_TOKEN }} #the password is set to the GITHUB_TOKEN secret, which is automatically generated by GitHub and provides authentication for the workflow to interact with the GitHub Container Registry

    - name: Build and push Docker image #this step builds the Docker image and pushes it to the GitHub Container Registry
      uses: docker/build-push-action@v5
      with:
        context: .   #the context is set to the current directory, which means that the Dockerfile  (to this name by default))
        push: true
        tags: |
                ghcr.io/${{ github.repository }}:latest
                ghcr.io/${{ github.repository }}:${{ github.sha }}

# not use the latest tag, because it can cause issues with caching and versioning. Instead, it's recommended to use a specific tag that corresponds to the commit SHA or a version number. 
#This way, you can ensure that the correct image is used and avoid potential conflicts with other images that may have the same "latest" tag.
# we use 2 tags for the image: one with the "latest" tag, which can be used for development and testing purposes, and another with the commit SHA, which provides a unique identifier for the image and allows you to track which version of the code was used to build it.